name: C/C++ CI

on:
  push:
    branches: [ proxgrind ]
  pull_request:
    branches: [ proxgrind ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: Firmware/Chameleon-Mini/
